### ISSUE TITLE
Ricerca Informata - Cos'è la ricerca informata

### ISSUE THREAD

**Issue by EduBic** [EmanueleC/Appunti-intelligenza-artificiale#1]
h(n) = 0 solo nel caso n sia uno stato goal, non per ogni n come scritto.

Fonte: libro pagina 92 "if n is a goal node, then h(n)=0."

**Comment by EmanueleC** [comment]
Fixed at [this commit](https://github.com/EmanueleC/Appunti-intelligenza-artificiale/commit/6bf583ebe60974dd25939155fd8db2fd95f563f6). Thank you @EduBic! :+1:
